apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: playitgg-agent-token
  namespace: playitgg
spec:
  encryptedData:
    agent-token: AgAMg1Lufp7ZNM8/esPb7wQ1XcT+OP057p4eU32uJG1x9C/UVVUUxJUNre7CPz5gO22P7/eJ3hP7EnkL8AttEPcOrMfBmbA7n8o6gUGRnfzOpipbflwfEUZO93CTx1VwO15f/n9VnGJkYP7ZROufZrtI3TUlgcsSr2ofLPdLdg0IuRO3+ESEXEDK65eghlE2/GQBArEev/Phi0TpzpruTTDMeoQkPwVirOYOGsf8U4GRwLZc5jUuFLJJzoU2Vr/Hf+Dz1ueF3kc97OcxiP1UKtMn05sUECCTsnUKXsGWaKqcF+ifwszX7eVxXqjiuizvIKZGrZ7H+UrtZSzlUR62sHFWVu8RjlIXc8Vz5J+Yg/uM6KAWGPC6Sl2NMX3FRzO8ivuX/tvBvGGxjdhUy9hU+64MirM6KDncqawsvjhUuwsALVTsvNSS1SEfDZc7j7lIj0esRaQ1lNBGPkNeOO9LzabWa0YxRBEGRwGRPJ/sYceCw93SdHRGfoWdTUALtAtQGq8S5c246tHBuh+w/+3arWDBFMckU9Or6FZOQ6mkdUt2n1/nTNznsZMxZlXCAQgE2kqlbkWyenWx0s/yTparuljeC7cDFkgvlsBzwAazLs1d35F6u4X2aGTfIIyhld59AMkhky31c93P+N1VpAwhZriDoYqRz/fHockScprdQbHW2u0MRIvoSafv3ic8D1mML7VMBQntxu1PwDdrWMmQhm1Z2iaFQ+UP0CS8y9/o+soOa4Tumk9oJb8HkRU90fuLv06tP6fQEud7fLsOvW0/Hm4U
  template:
    metadata:
      name: playitgg-agent-token
      namespace: playitgg