---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: playit-agent-key
  namespace: playit-operator
spec:
  encryptedData:
    secret-key: AgAsEuNgS9F6d/RHkifYwsXeOAZVdhv7aYUkV67x0+bs2yN6fkONW7vOjpGM3XqWi5aoMTpmxKv/MhzE8ZnHA3At6DAw4K/XldBi/beacDP6VbAPGlgqLFSXU/B+YSqscJ7S/S6vaUXqDLCeHca3/BokO9+p4rI06BoPje+PWhxawqGWepcC+hoY55q8NP/GJKiZWdTxTl/HFC1W2yDheuJo/3LKmXuakDH8LRAcwlL75GIOig4UHzmHC68dzQEIuu8usPcQTAhgWajc69jAg8zUSH3eZs1uxIPsCWr5Obz4ZhkJ4NZcW9ejt7kmNGLIu6NArCNhyj1hIAmuboLrj8ede/msbIPkgaMTGS6d0YOsuwiMoIfPEnDIs/e/ivCe3rcgGI+8E/0TjIeLDvHQOude/EGfFDwZsOmkQMPWW8qFLMk6whEHSnDZQrELmJENbJZFO84kL4A4RoZLhvNt9GWIhSEojGljfWCrZh/T7PyM6yYnUTe9xBf3igeomVBRXO/GKAR2pjezlNbVVJfBgdDuJRhR30V7l+U6gS2kBZOYqoSvwyL77fQ82tgYctPduFOqJTlj8tZomR6i9FBmZICc2rtEKFetqkw4taangRBlQlIeC5xhxBTlX31ygTkK3TjpoohlarwF21OAH8so8IPywoYn+TzcCsItE0rqigFWrNaC1d8+xfTS7aUcQzsT9+hcfbdg7aOdghYfvAbftL/omKOXtRXTtzLs6S4tnX0Tio00Nrd1YErGIMXI7REYYH5n/ys+Op/7IPUM1TZqjVHc
  template:
    metadata:
      creationTimestamp: null
      name: playit-agent-key
      namespace: playit-operator
