apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-path-provisioner
  namespace: local-path-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-path-provisioner
  template:
    metadata:
      labels:
        app: local-path-provisioner
    spec:
      serviceAccountName: local-path-provisioner
      containers:
        - name: local-path-provisioner
          image: ghcr.io/rancher/local-path-provisioner/charts/local-path-provisioner:0.0.32
          imagePullPolicy: IfNotPresent
          command:
            - "/local-path-provisioner"
          args:
            - "start"
            - "--config"
            - "/etc/config/config.json"
          volumeMounts:
            - mountPath: /etc/config
              name: config-volume
      volumes:
        - name: config-volume
          configMap:
            name: local-path-config
