apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudnative-pg

resources:
  - ns.yaml
  - https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/release-1.24/config/crd/bases/postgresql.cnpg.io_poolers.yaml

helmCharts:
  - name: cloudnative-pg
    repo: https://cloudnative-pg.github.io/charts
    version: 0.22.1
    releaseName: cloudnative-pg
    namespace: cloudnative-pg