apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: applications
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/erikandreasklokk/homelab'
  destinations:
    - namespace: 'argocd'
      server: '*'
    - namespace: 'portfolio'
      server: '*'
    - namespace: 'minecraft'
      server: '*'
    - namespace: 'immich'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'