apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCjOJuT5p01DgXGFcdPvmf27wKl/jyd1CLz2eAUh4ZMV21efppk21Ezx/zmucXA4+4ZN+zlAZZL4n4jPG2NuTR4CR5o7G/+rEl4oQcS8fFiH+leIuP6apKCyBLnjqX1kgCYuMFrfV6tfnCi2dSvfvktZL+B5s/0zQm++JGzKnv39pk9Zh/puZTpR0qiWQuvBiUoIt/jN4c+x9eKXnatAjDbMXMvj5c7xnwRukvR5/TVi8N+eAOaacgwp9JZ+5uOb08A/PYLbcy/HNnmqao/fL8D85SczS3h8IGld8m6Bt3LsZv+Moa3C8MFKqfCHvSCCi8dpNUFWIE0vR/FiWv/xa+I6b2HGJsSkASA7R83UOpjOXRXWDxeueQc4uhxxb5NRaHjNBKF5e+tkMY3B+LJaGa7axFhE2UMZcNVY9U/OfMXaZqAJ1yfITIIIwJg1QbLDz7NNulRNOSCGLmNm/ryQ2xBCoc+j3a2xEO+PghbcC1WzhYFl89JHHhG10usWFrezhYLJar8JGJRhwyYgJw8hzhfWcF/FJmjQx2V1RcXa/VTNY3/YecwWkTw17S9USeIDYBWFUBUJIvXUXNyWoiDa+f1kqg5NCIcU6p0Nj7e3sxu5/nywYmvpid51v5oyrbrOpdAMXvcqCEHXwGyIQi2hOBllhIq2NZL4WB9SYGCwZPYzchEJOPGXA9TKLwwwiIyiNvq0vcl0IujBLpmZYM7mZdATiHA4UbNrWziXuTETZpQ7bKDYaWEeMxS
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager