apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAHpGOR1p0Iilr+MCKLIL5awRBHfV+GiIhK4sVwYciwOKyr4KavymlHWAsLaQdY05gRoGIzYm8kD+vJsn1CbjwVKBvHPe+aY8+leZeHhtUBc8YTeXvfiAccsuhGDJiUfayfdGxA3H8ekYK+YGd0+2/HZXQgSJAd4sYaPV/3yg2UXZAAf7AhwyQlQrpvDuX2ftGYtiTcKna5+Wp961LbY7LpxErlVdJq1F5omtp97PRDSLweZrizMc6uCJsJ/w9+UzVPTzXAR7ctMNsgRmeN09zTp6g9LIwA/qjUQG0UFwTforTndxiXP2umcwIaQT2ZYo/AVqbaQsE5Fn5iFpdJPCJDzmUqZo8hMFUZNkPPRhoI8/0jZ3XkewcZuTeDxQe0DjcmD8m11Jqy0afVQOgXNx8Zg6KBxpAMvpNb4fMxb7UGlJARAsoPiF0/jzsauxOe7A3SZe+yZta3rLkfHUKrVigOJRf3re1r6ynLfiKUNR0bJYD/IE5Spe4EcHKOdn8L4rGVtfGRKr34UQOdem6CuTjzNsPbboN+rRJNcNmFUHeB4+ih8kiiVF1YbquT0d3ZQLuSBPYjAhQ+FeZ0rCIEfFbS71yxeNbrZVi2RWcRbaYMwtGmrd8iPRa3/aKdDcVFbUViLbhh77hkPBI4hby/Tu7Rde/qYSPaYRA1Xu4dFSEFOHnWyK2wqBvMEsBsfiAtwEnU9bE8JU+c1hlCEwym5OYKhpPg1BpAiGstz95IhWsr2b4eFr72F9t+/g==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager