---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCmwZkdblcTCY87/MNakzTFuXoIJlYzZeVxifp96N1EQpNL6isHYhL9UBx2zAcEyWPJbGMgNNPSILU8/619MNi+eKfgaMbTkoL+SEdU833JX/J/ob2uAlce6cdV1CgSQriKjIWFQHQzUdQS1SmZBHLj5eACHIQ0iZe8YBj/444X/B62fBqTs5/78M1/lNibx6zpNSTrbu9RLKbD+WVm0RCwyDzU57/KBsXL+XYCxxLyyZHugud/TCl9D1Pw94VmTgCqcDyEFVZWaPCJEEG/q6TkPpQWgGNl6sfI3/ogPxFxwpCHwIUqOBVHrT9dQIbwTFaEyQI87GVLpjJO1Nlyo+HsEZQqESQ5ySGD8OTHedS/Y9t2sTX5oo192hsa6WMZaE8d7kKJNvSvjyo4FbWNdMqDeKyAVE8q7FjeL7+7NKPvFhPSMvSZLhTScBeJAG+1IO27LRN2vWGsNyNzEuCjpOJTTZHemNaWtRK0oacb9Eh2S9wWLmrqN0D2mJZl0YeEerHW37h+92KgnUhiKPeG+T8KmLRgPVq19dplgXefAp9RxiziXXQbOHjn+9RXbPInmAxQrrmFXpV2nZue1Oz0vOfYMb/b0jsDF7a08OnaoFzpcLK7jKVXizKEIUicAbNItr2hUDJxrHauQ84wt0G849xu1RhLwKaz9zxcUF02SE3WhrIFNt4L6TinJnnzpgC5maWy9QtG0Ncm1hJz/nKbqnRoYIFL/hQqXg==
    admin-user: AgB9tPxR5dDJWX7TRYbJyJx0PKvjLiJIKQpwb1cmwb8hPGZvaegdvWpO4lLaxwqzL//sEZboHEDn+4Oa6f0s6by+WItYRCeURdCjWAPTpBENbHF6Fn/0xxKwSjBaeXyQS9PH+eI/YkrWN3slO5cZzwtt2RywfAWatz8Yg4qrF08b0UL4sxEvWxHLfuEET4UkcLWwsUWVPAqjYrkZ/pZwmHkXAK6IoeFTxACN7XZgdS0043dqf83GBRC+9A226MEuGW47XJio0NuXaAZI9m4dt/2bdiR1lIhHiDuqXsTXPrh37NGOPg8uuHqvQwuj1RsbhX6TlC0n1OQGROLFTLTSjKzpQRqhvkwGP2pF3BTJ9CwnlvKcVxlnfepsWrNhi3NeUq761QxMQksrDnLQ6OXeqrjsMzE1ofwa4qKoaYPcTIomtIVqm3pdJyKoQ9jzsRSuwfkK9WsVxN0hteaKInVSmjLQL9rGskl5BQ2dBc2OqyJE7H5KjPts71Lgg9W7nj0wUe3NNCX+pHexHS96GS5Gzuih8HFOslO4XgMbMOBdIdb00dwC+JPu+HFd7nN3P1amhCdnD9Rs2IQbSxt7OHB+45RdeybOz34kif0Y6bhGxmsEW7JztZ92ohjWr/DAaoxOvqE9aM1cl139ooXfbASb6XXMeHnc3JPsGLutZ1H/G+Om7oU+kmnLXCTFm7XtWUbfuZWayGKyzQ==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring
