apiVersion: batch/v1
kind: Job
metadata:
  name: bolig-db-migrate
  namespace: bolig
spec:
  backoffLimit: 4
  ttlSecondsAfterFinished: 120
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: ghcr.io/erikandreasklokk/bolig-migrate:main
          imagePullPolicy: Always
          env:
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bolig-postgresql-secret
                  key: postgresql-password
            - name: DATABASE_URL
              value: "postgresql://bolig:$(POSTGRESQL_PASSWORD)@bolig-postgresql-rw:5432/bolig"
