---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: bolig-discord-secret
  namespace: bolig
spec:
  encryptedData:
    webhook-url: AgBrcQEBuZEl4gMG5uR06zAC3W0yLO0vedU6kxB3vxcMzzDqjCN8+3BF6W27S44NIgEbCC6D6hRkv8CL+0fSe3oBH9rybmoZG582Y9osJkaaPBqxdi/3nzIxwccSVaMukVaJUJqgDoWKHuyiVoa6gp15nPj8QNeWdDBKxD0hxJrGhOrxcfYqp6jZz23CRoyIKchBOkHXrU/4B5uQUlPAY+9rizecpc25sRnQIkv/FcCyeMGNEu53l4cVv5OFOqRAsG2zzF7eNCBOHUe4qRAYPhrAW8YxRNqwrg6/27afFrAjvFjBrasBe5aqNDXg194p5ylDoPMIvCKhqMy88Zmjy14KN44iuhrhzoAHFDYFwumpm3pal+B9md/CERbJ9xc9w5pUUfk2fMcvJ5huoGrjBklSj/ygsQMpntAHTrkcUtdr5Sk5xb5kML/S6lRfOSrMOyEr4q7LBSFc8obt3VBR0JLv4ZiGVFhjQglR1ui8Xhb0on+n0dpbG220mccrvgqqp7UELZttT5UNJiI+C0danCoHJV5eIlAXAbcWMAuKafGnTyOo3dpEt6st0tVjCZd+WDG4MpvVmjxAHvMLyTE+309V3BfeK1LM10vt8RG7PPNf+8Cch5ZGAzfSx0y0WYdCjdshuAdloddJwIxDCdwJwIZVFrStFMf7c72NP4c2rU8Z7zIvuW8Bz6DooiGQ87iA9kQ+NkdCxbFen4mWii6y95NtfiO48UUqokE+T/dEZ27dB7Y1+q3/2CGtQ4B03gb3n1jSLVY9ziHV6Vm2b8BVH4KMIBwMGV6BlAi2BYzMYo33nUqp2Ol89VI4KTrICI5LcSX0sFRKiuxaq//Y7uppHDKip3tW9+Ydb2do
  template:
    metadata:
      creationTimestamp: null
      name: bolig-discord-secret
      namespace: bolig
