apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-hardcore-data
  namespace: minecraft-hardcore
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 50Gi
