apiVersion: v1
kind: Service
metadata:
  name: minecraft-hardcore
  namespace: minecraft-hardcore
spec:
  selector:
    app: minecraft-hardcore
  ports:
    - port: 25565
      targetPort: 25565
      protocol: TCP
