apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: immich

resources:
  - ns.yaml
  - postgresql-password.yaml

helmCharts:
  - name: postgresql
    repo: https://charts.bitnami.com/bitnami
    version: 16.2.4
    releaseName: immich-postgresql
    namespace: immich
    valuesInline:
      auth:
        username: immich
        database: immich
        existingSecret: immich-postgresql-secret  # Reference the sealed secret
        secretKeys:
          adminPasswordKey: postgres-password
          userPasswordKey: password
      primary:
        persistence:
          enabled: true
          size: 20Gi
          storageClass: local-path