---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gluetun-proton
  namespace: media
spec:
  encryptedData:
    wireguard-addresses: AgAaXtw3HUPWRIbPjSQON4iokJtqrYfFav8ZLpwDRVfYGY/MdToH9twRCwRmfbyLmiychrk7jLCIGCvYMaaVcyy7cEPqX2sefFWw+XHF9pnVvheFaubplcjiPQcZDRR+x0LTTZY0tRiEPnLCKrTkZCMj/MgA2keRCKBpVuhemfFzBNdsLvXWfe6FQcghRVS6iKFdh99T6Yxh3Yidf+lWxQJvq7rQujfRmp6cx2ntvskkhInmQkawrR0uMthPt5GsoTgC/xQadFPp32Y3rKidtlosVFB/rv0syV6UN9PCaTIPmQH2V4kRRCoI3lUSdyBigJXVdriWfjdG1mXHN5lGu1cqzhRjPNqdoHj11H6DfTmV9y0djLS2sZwPUGHkuGOLeRJ1gv8nO8xAqocK6C0zcnowGQx3mYkRFwLQpV7o/dRyJGd2W5StOGnmL7MD1PM+lvu3R38bhJnE/q4N9EpXWVKOFHXj/rMSg7lfhxIvjO+39Ob6XAag5fOBJwIOQptR/NjkTkf0uoAtPVrFOuuXfohfIExNcc8YwUcz7l725dCZNYaiD3XSgyyJGf6ZdsEfkvIx6sk3PBA3hc57XET0fYMe15PH7GHUJbAUYeImoodfhnZAZFYkxmqTQJTsNOqVaDUgPOgRTq7mMHX4I/iaxeTu0WhAvO8gMC71zbr4ZvFmmgeHRMIfEL90BX1Cl+UGXHFwHJ7qetH/vJAwcQ==
    wireguard-private-key: AgA9kv4Sim0YCNdFTPwO4y1ywYCaA6qkidcNbL4CuLoJRzJvBKbO/n9QtLWVxvZnTRzlLqT4VvUX/Ewwv+rQ4mfsu/0k2xYbph/dDZayr9HiBrVkq5b5JBBIDbVdONX5f67LDbcaV487m42bnwe2s3G5Zu9ZhShYY4qo5Rir90+bIXOySWHRfOyPij+cEd6OsmYsNVhlfwepbjNXwuNK62fb+JDgGOtGhKhKiCblc6XRnFIt9JfFk2z4Vqu/1lGyXbB78wJDas63JHFDuUQKB3584UpthPlW1MFpWpkaCmGfSCaFscZ4WdE7qweWH40/+k9CL2nyc5t9cMybW4TTI4OQKCbIQi2Xo0XQdMAuEKOM7Pq6lvfcYtr4KrRXR8zv8tHTRMo92RqyxxckIR7cVhlB/SyRcckQ19m8rkbqUqYghFJ4guyHxlrLyo8V9gaywqAtUXHNPqb5nWbjGMJGFuzhCy3vIkvQq2WEci7rWqjBnPFTJw8DMu1N4GE//OjEnwGgcowx5jvvOZlFLJcXI06LKmvZyg1rNTyEhsTDRM3yMnhDXkEo1DJW94YrD83Y1V4oxxFfkKz8E/WDq+9/TabVZ4wGYsoHlECrQMHhKethznovItk0lljbofvB1JCAL0z8iJlYpoLT98ziD3Lxul5UGv8WS2SnH07z7qIW5sm1gFxlNT0+kVxqtXYSYFyhNQPW+TYkdPUl4iyDrliNXtplZ4UdQFnXslT03jis+Z4k3yBGuXjETzJSsTAtXQ==
  template:
    metadata:
      creationTimestamp: null
      name: gluetun-proton
      namespace: media
