---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgDSEJVjoJXIadPlrmOWiHj4/uygsLCnzZSXCKnD91lyH9UTWYKWMGdnsdLB3jojVKe8pBDQHLo3FlDJtEoHAJYM/J0/s7StypnZK9mjhTWmQeh305CZVxpNv5T9eKiSzgys+WSNwyb8Dh5tP8/1a+NfROoytakzifC+paa+JuRawSlExJGhsJN7Y8rXiem0xdFhffnheuefGieaklhl+yE/Y1y9MI+SsOPJjCd7zcN/Yu9P1EbM0CfAewpC/iZsDXWDQjj24PZXuymEhu+LGDlIx+VvKdEd7neGiBhcvmGd0MQEoRkn+FYO1YMrgAdzpWKBIovlZL1foSooY0U0uCoXIMmZGrhLLGjYErmuY6ta4EtvPTOktyiB35mH6C+E0zGE++xK8aV5wXBmBiIbH8EqkT0ZZRc9t1cvhtDcOn6Hp+2OxEvgOhobAZm++RktgP4OObhwM4LxINiqg4hSmLl9A3+Ucx/PvbbM+15Klk7NLTJN+ZqqX56hnk1nqWCRMjeto++AOUrvAQexloEy6oxZBLc4CFC7YTgjS5LsyhlCPifAmV7StANMcfgUQq+qCl20uA4w0byBoDLsmaQ41j1+7P/UGKqfWJyHvTK+EYPbTKLEJH5EWAHw3AN4x71O+qPQltmdaMkkx123EA3hcbF5r24NpNRWByJJC+4ub9MhRzlKZW6TwZs4m/yaX+k3+3R253ANGlZPm+NXkO3FhVUwpxyHfOvzMMvao0AZHF4fBH5fVepoHKaeQCITWSg+yk0X/UX1wEwgPrdtMgonElIG1Kj6GV2HkOHekcWS5eLVLqMkM0r0aSq2nT9OLiczv9Y339flt9UK785/muh00dT2FsoeeTyLJsjIgDdTTK/Jw8aZMjDXWwNcFebdmiAqBATxnEtdQpuRYCMWJIIsV9OjkNq3kuC/SLIyOsgRmoNyVg==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflared
