apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgB81FdFIX90yLVVJM25wudY5h4LrkkhNFIBvCC1ST+3siDtdBX/4N4ZB1Kogb2s2fBtvfzfUy7+c6yFLRVa1Z9W8vilayj6khuAhd+MLRGxumZn4Wphx1PVpmlaXkGUxfhcRhzXHtsdfilShGBdJyc0DMlfqwMJxb7zYZvUVEcLBodjOIaV2gasEgHXOYV5/RUpmceblEGtVkRBFKSTEYKPq3ZXNQ0cUKgpcQwTWQT15fKIMdTuVMFtyf+KoVfj7YBPEj/NiQclCxW4zRkowkDYE2lg1qhTIF9lfUjHXdQSofxdw5uyqecPGP2gWYYm2e6QRg+k/N6hYpIKw9vek81fqAguFelfJjUODRTbPYxayMmA+he17j2sLck9LEmXjhdwacsXe/cOe/xCGhte+2FBt3yFM1/NGeg4ZuKVK8wN5Dikw7L9U1aL9UxOJdzbAELrz201HLkSkGfxy3IUl5AT73MqK+da2t3SA1vT9Cs0i3Gce5P8F/+Tucs10IDXVqiWcrpugDd8pXOrmOdFSsttQrR6/ZwQXT/AzVW4yiBPXRKMh4Jeq1BTkHK5cgbXy8T89X41cCrNCYZeNIjuHgTsvQV8Z3MxsYizTwoXzpJtBBtUP0vS0GAkyNDzs2FL1m0gQix8lljXMA3OUr9s0VREb5eYwoQVSqyBSnWaqd1VOqMnmhOIKf58YQMYxVueS6GNHuMrzJH+IxMbCk95j+Cx8ZT8O29X195tvZX+tUd6CIjS7GUtje4IEihmurigTsGyYgq5IzD8Zg1OCBHzlAncHKXlxdm8329OxRLd9uX/I1AQ/o2xPqU3UKxftXKKYn0vGGJ9sFmcAZo5jqzg7r32RiJCHFjBe6lITg2p3udzw47p/dd3IDC2m/twYuM+Hu1ZsT3REU5Y8UprllOK1AfVRv9Wrj1jGfRaFXkp3KTbZg==
  template:
    metadata:
      name: tunnel-credentials
      namespace: cloudflared