apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - postgresql-sealed-secret.yaml
  - postgresql-cluster.yaml
  - pvc.yaml
  - http-route.yaml
  - deployment.yaml
  - svc.yaml
