apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-db-secret
  namespace: immich
spec:
  encryptedData:
    DB_PASSWORD: AgBFqhK20u9n2+Rxk/JPBKSlo3UTvgJ1aAULsuhke4BDDeFpP8XL23QRNv7cBtgFdPI3wX/t89gILARqZGczhR41sNkAjMyVnEcTB6rB7ohtHZUPkrHBzEAGN+bG+zojEDI9AEBgioZ+LjRDKHt3m+4xjQd/Tyu4w2BEJgH2M769BLhla2xQVW9z70e/LtmOTG0zlr8L5rHyN7gM547oSQZdyc3CO50cZegTv/iyESfTpmPABO2rgf7446IlEYdga4gEbflYJKyWd7hYoP6jSE1aeAtuEoBPfyjPYznaU/2/zdPqwSNpIA22noAAABASPXwiE9WM0LYzaMG8/e5FhFP5K2sOMIo4p3BcvY/JPt0KzDUI18JO7za0GHMWvOOa4QVHgOiKq1GmQVqlv0DER3VQTTXsO9gLtl/pWDpFZwlpA65O6gzBtbXd0F29DvCUHSMtQRk/xK1/zjEQRNvRPcLimKo/PV03VzJlYWxKNqysyUnEpwOt8aTqrcaD6cIwjMPxFWS3hG+UTrGEZrKdPUUr7F/htZAfMpKuEi8+lagGWpHBsb1D/xGgdriRgXsyx2UvQqQkbh+K9T+d0hx8Tpgn1fdSrplyzqfEDwAC1GfaD3nnAFIZ7uLuUEV2vzoOk54NTOwHFSoPF1xJSPX8KGEVLYnttMtr6CnDfz0PE6zTIDbStRLdqGCewossIFhQZXR4ShtpBAlDOCxbzA==
  template:
    metadata:
      name: immich-db-secret
      namespace: immich