apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgres
  namespace: immich
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.6

  managed:
    roles:
      - name: immich
        superuser: true
        login: true

  bootstrap:
    initdb:
      postInitApplicationSQL:
        - CREATE EXTENSION vchord CASCADE;
        - CREATE EXTENSION earthdistance CASCADE;
      database: immich
      owner: immich
      secret:
        name: immich-postgresql-secret
  
  storage:
    size: 20Gi
    storageClass: local-path
  
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
    parameters:
      max_connections: "300"
      shared_buffers: "256MB"
  
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "2000m"
  
  monitoring:
    enablePodMonitor: false