controllers:
  main:
    containers:
      main:
        env:
          DB_HOSTNAME: 'immich-postgres-rw'
        
        envFrom:
          - secretRef:
              name: immich-postgresql-secret

immich:
  persistence:
    library:
      existingClaim: immich-data

valkey:
  enabled: true