controllers:
  main:
    containers:
      main:
        env:
          DB_HOSTNAME: 'immich-postgresql-rw'
          DB_USERNAME: 
            valueFrom:
              secretKeyRef:
                key: username
                name: immich-postgresql-secret
          DB_PASSWORD: 
            valueFrom:
              secretKeyRef:
                key: password
                name: immich-postgresql-secret

envFrom:
  - secretRef:
      name: immich-postgresql-secret

immich:
  persistence:
    library:
      existingClaim: immich-data

valkey:
  enabled: true

server:
  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: cloudflare-cluster-issuer
      hosts:
        - host: immich.erikak.no
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: immich-tls-certificate
          hosts:
            - immich.erikak.no