# Tailscale OAuth client for the operator (Devices:Core + Auth Keys = Write,
# tagged tag:k8s-operator). To rotate: recreate the client, then re-run
#   kubectl create secret generic operator-oauth \
#     --from-literal=client_id='ID' --from-literal=client_secret='SECRET' \
#     -n tailscale --dry-run=client -o yaml | kubeseal -o yaml \
#     > setup-homelab/tailscale/operator-oauth-sealed-secret.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgCc036RntrwQie804qnQim51uVFBT9Az8DzqiwDSV5JWxh7n7L/gS+hLFH6/aYxhqQjM0fuayTxaHXrTxVkhIR/WmAXuvdsnDNOy6zJNx2M8GIzWco6n5Lq0PaI8grO0sX82TJ1zW/STCubA3SNflpgU4lO5PPk8P9T3oB1MY9n69ktd2zMKriZDZNXoz0/6DRdQQc/ROdPTTNU/PwGS0YFlmgiig7bHPztSftz9tpx6ONR1tT5/Tt4UchR4rDx8vetVN5cVwN9kJzErY0McpdK9+hU2iOPxlSzVJGlFPByww6V1ZGoLXAXuKJbCSxL7g9bYXVJ3yj3IUUKK4hqV/y3c7zITIexga9N9UJlimDSg4HLGPv56lBQsSmuK2L51ljDLNEytKJ8H5+LS1MklAI3UGS81hOmA+y0eDeJXBGKuH2dTcpuaERUnHDwyDnvQ7nD3wLnudaOBuJH7eya6CvTgprDDOcBatKYTnFDt0TFTCSsQlNIVS4EopIVUVyrXFVnX8QZUnRGCVSeeTMttalT4JVjkBiShyquJTT+32Uv9DWTsv2/OWTduXh8LKSdr31WiUKT134ittOfjIW6xljISm/I/iPEAxgbkOqKqI3VwZM6Uo6R8TVGUZCZZ3syLy+ubieKvwkFFMkvWpHpKVDyzz4fysV+ZZ3kPL1m+eC7ejBU/Id0SkJQCcrAWUcSRs6eAL9QTa/vBb8CWk3ISxA1Wg==
    client_secret: AgDUVVJ8YS8ZMFF5ce5tb2cv+YjpZ+pFjze0pvyNSpBiPm8RZNFbyubtgMub8jWnLDuLeE90fFS9jkgpUi7wrQd6chV6wOxn1xXrXJCVomonrzPNhPVPPjMa0uyRxJOzEktbuTn+xRj74RZVYTST/sH07VHNYqp4M72gBu/7e1/R2w8RwE64ZN3oVSRwIWtYZJjUSSz0V8zLpNhrhHJUtQvW0mUbGFUtk4NMh7mo8g6sUuYNGIereeKkBbhsfOzWa+yx18AO7biXV7WdkANFxwtsOkWFlaYIZBRH8J3hl+by80mm67vzRlaNYcDQKN2y8yk40TbZ3+OqD7i7zfFEGXzt9Blt+RvhWpkOhAbxBUIVMQvJlUV6XciXboh0Oi1YCeUvlv25OQTObtcX45rIrsVZTPbHeEiet9jhZeB69DHtsNCJCCxwjMp+jJV/Qvf6f/yL0zlSJ5urJ2JD3ZqnUA92qMcV9/R5Dk786lLzV5I/E6JCeuEVLYvWzo4fW6jcRCxIekiEXDUNugop9S9CgpYMBHtohCK7DhXTUMN1PJkHEm/4IekR0ufC2PhsAC1VRZB6q2+6rUBZiGyrh8ZyQwHKTdB/ASf1bgovsQmy5gYmb/OEzE7jyFgGShvfOkyF6zaT0QyRhZNcvTjGoHg+ujf5xyCDipuwcFkPNQhqZqtKEiB8hc3pckv3cLNdKFmGb+OFPCnmsce2bwDtUUDW/I7btRxJiHILaRcaZfTVZ1w8JbO6NTLhnl4btussVX2+c+KDE/TllOx68rzGhnXrXbk=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
